[build]
#rustc-wrapper = "sccache"
# 指定target目录，用于共享target目录等
# target-dir = "E:\\work\\cache\\rust\\test\\target"

# 使用交叉编译进行编译项目
[target.armv7-unknown-linux-gnueabihf]
linker = "/opt/cpp/linaro/arm-linux-gnueabihf-gcc"